# Generated by Django 5.0.6 on 2024-07-24 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comments_replies_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequests',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comments'),
        ),
    ]
