# Generated by Django 5.0.6 on 2024-07-24 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productrequests_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequests',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='productRequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.productrequests'),
        ),
    ]
