# Generated by Django 5.0.6 on 2024-07-24 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_productrequests_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='productRequest',
        ),
    ]
