# Generated by Django 5.0.6 on 2024-07-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_productrequests_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequests',
            name='comments',
            field=models.ManyToManyField(blank=True, to='api.comments'),
        ),
    ]
