# Generated by Django 5.0.6 on 2024-07-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_comments_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productrequests',
            name='comments',
            field=models.ManyToManyField(to='api.comments'),
        ),
    ]
