# Generated by Django 5.0.6 on 2024-09-18 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_currentuser_comments_replies_comments_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequests',
            name='comments',
        ),
        migrations.AlterField(
            model_name='productrequests',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productrequests',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productrequests',
            name='comments',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comments'),
        ),
    ]
