# Generated by Django 5.0.6 on 2024-09-24 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_comments_content_remove_comments_replies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequests',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='productRequests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.productrequests'),
        ),
    ]
